{*------------------------------------------------------------------------------
  Shared Include File
  
  This program is free software. You can redistribute it and/or modify
  it under the terms of the GNU Lesser General Public License (LGPL)
  as published by the Free Software Foundation; either version 2 of
  the License.

  @Link http://yawe.mcheats.net/index.php
  @Copyright YAWE Team
  @Author Seth
------------------------------------------------------------------------------}

{.$DEFINE UNICODE}

{$ALIGN ON}
{$MINENUMSIZE 4}
